### PR TITLE
add bans to matches

### PR DESCRIPTION
**Pull request by Chupalika**
Screenshot 2022-05-26 02 13 09

Screenshot 2022-05-26 02 15 37

### CODE REVIEW

**Review by cory2067 — COMMENTED** [review]
the code looks good to me, but im still worried that this makes the schedule too wide
can we move this to a `<Tooltip>` for now?

mockup, but open to other ideas:
image

**Comment by Chupalika** [comment]
🆗

**Review by cory2067 — APPROVED** [review]
what happens if there are no bans specified for the match (e.g. for old matches)? should we just hide the tooltip in that case?
otherwise looks gud to me

**Comment by Chupalika** [comment]
ahh, you are right, I forgor 💀

**Review by cory2067 — APPROVED** [review]

**Pull request merged**
